// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";
export let options = { maxRedirects: 4, iterations: 100, vus: 10};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC91c2VyLXNlcnZpY2VcL2FwaVwvbG9naW4iLCJpYXQiOjE2MjMxNTA3MjcsImV4cCI6MTYyMzE1NDMyNywibmJmIjoxNjIzMTUwNzI3LCJqdGkiOiJVcUFld3puSmhTN3NjWjU2Iiwic3ViIjoxLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.X64xnsUPAzS0fYxxgT1bvh-yYVGgl6lXa4WmmNWuaLg",
    houseId: "1",
    userId: "1",
    type: "house",
    id: "1",
    hostId: "1",
    URL: "https://api.uhomefcul.tech",
    undefined: "https://api.uhomefcul.tech"
  }
});

export default function() {
  group("user.microservice", function() {

    postman[Request]({
      name: "Login",
      id: "ddc2d403-de92-4d7e-b7e2-d62d04ab2157",
      method: "POST",
      address: "{{URL}}/api/login",
      data: {
        email: "teste@gmail.com",
        password: "123"
      }
    });

    postman[Request]({
      name: "Profile",
      id: "5f4fb060-77b4-464f-ba60-bccf302fbd62",
      method: "GET",
      address: "{{URL}}/api/profile",
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "CheckToken",
      id: "03e99378-baa8-437b-b585-a65db4f6ea9a",
      method: "GET",
      address: "{{URL}}/api/checkToken",
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });


  });

  group("message.microservice", function() {
    postman[Request]({
      name: "GetActiveChats",
      id: "060c6158-7b5d-4ce2-b481-729ab7ae00d4",
      method: "GET",
      address: "{{URL}}/api/GetActiveChats",
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });
  });

  group("house.microservice", function() {
 
    postman[Request]({
      name: "GetAllHouses",
      id: "b745b39b-ffd8-49db-8edf-453cea164d2a",
      method: "GET",
      address: "{{URL}}/api/getAllHouses"
    });
  });

  

  group("transaction.microservice", function() {

    postman[Request]({
      name: "getAllTransactions",
      id: "a043c986-123c-4c1f-b35e-deb4ec0f5c78",
      method: "GET",
      address: "{{URL}}/api/getAllTransactions",
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

  });

  group("contract.microservice", function() {
    
    postman[Request]({
      name: "getAllContracts",
      id: "560dc75b-fa35-4cc3-8a5c-d811ebd09a7f",
      method: "GET",
      address: "{{URL}}/api/getAllContracts",
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

  });

  group("review.microservice", function() {

    postman[Request]({
      name: "getReviewsByTarget",
      id: "b04f85f5-8c9b-41e7-b162-e7c31138fc07",
      method: "GET",
      address: "{{URL}}/api/getReviewsByTarget/{{id}}/{{type}}"
    });
  });
}
